version: "3.9"
services:
  internal_portal:
    build:
      context: .
      dockerfile: ./packages/internal-portal/Dockerfile
    environment:
      NEXT_PUBLIC_ENV: developing
      PORT: 3000
    ports:
      - "3000:3000" # outside:inside
