from pydantic import BaseModel


class ConfigSchema(BaseModel):
    INTERNAL_USER_ACCESS_TOKEN_COOKIE_DOMAIN: str | None
    INTERNAL_USER_ACCESS_TOKEN_HEADER_KEY: str
    END_USER_ACCESS_TOKEN_COOKIE_DOMAIN: str | None
    END_USER_ACCESS_TOKEN_HEADER_KEY: str
    OTP_TOKEN_SERIAL_NUMBER_SIGNUP_INTENT_COOKIE_KEY: str
    OTP_TOKEN_SERIAL_NUMBER_VERIFY_SIGNUP_INTENT_COOKIE_KEY: str
    OTP_TOKEN_SERIAL_NUMBER_LOGIN_INTENT_COOKIE_KEY: str
    OTP_TOKEN_COOKIE_DOMAIN: str | None
