project:
  name: &project-name marketing-event-consumer

image:
  repository: ${REPOSITORY_NAME}/${IMAGE_NAME}
  tag: $RELEASE_IMAGE_TAG

pod:
  labels:
    env: "production"
    cluster: "esen-cloud-production"
  resources:
    requests:
      cpu: 100m
    limits:
      cpu: 100m
  priorityClassName: mid-priority
  envs:
    - name: ENV
      value: production
    - name: DATABASE_URL
      value: $DATABASE_URL_PRODUCTION
    - name: SCHEMA_NAME
      value: esen_marketing
    - name: AMQP_URL
      value: $AMQP_URL_PRODUCTION

autoScaling:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
