project:
  name: &project-name marketing-event-consumer

image:
  repository: ${REPOSITORY_NAME}/${IMAGE_NAME}
  tag: $RELEASE_IMAGE_TAG

pod:
  labels:
    env: "staging"
    cluster: "esen-cloud-staging"
  resources:
    requests:
      cpu: 100m
    limits:
      cpu: 100m
  priorityClassName: mid-priority
  envs:
    - name: ENV
      value: staging
    - name: DATABASE_URL
      value: $DATABASE_URL_STAGING
    - name: SCHEMA_NAME
      value: esen_marketing
    - name: AMQP_URL
      value: $AMQP_URL_STAGING

autoScaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
