apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.project.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m # to allow to upload large attachments
spec:
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  rules:
{{ toYaml .Values.ingress.rules | indent 4 }}
