"""empty message

Revision ID: 22f012f43711
Revises: 609331b48aab
Create Date: 2022-12-02 14:27:24.763869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22f012f43711'
down_revision = '609331b48aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ecpay_merchant_trade_no', sa.String(length=20), nullable=False))
    op.add_column('order', sa.Column('ecpay_payment_result', sa.JSON(), nullable=True))
    op.add_column('order', sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('order', sa.Column('delivery_address', sa.String(length=256), nullable=False))
    op.add_column('order', sa.Column('airtable_reference', sa.String(length=32), nullable=True))
    op.drop_column('order', 'payer_end_user_reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payer_end_user_reference', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('order', 'airtable_reference')
    op.drop_column('order', 'delivery_address')
    op.drop_column('order', 'organization_reference')
    op.drop_column('order', 'ecpay_payment_result')
    op.drop_column('order', 'ecpay_merchant_trade_no')
    # ### end Alembic commands ###
