"""empty message

Revision ID: 95bdde8229cc
Revises: 96c6a6f4a571
Create Date: 2022-12-29 18:30:56.515198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bdde8229cc'
down_revision = '96c6a6f4a571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_product', sa.Column('display_note', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_product', 'display_note')
    # ### end Alembic commands ###
