"""empty message

Revision ID: 808313bfaab1
Revises: 75de2ac73ab0
Create Date: 2022-11-03 17:06:03.644425

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "808313bfaab1"
down_revision = "75de2ac73ab0"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "service_product", sa.Column("effective_time", sa.DateTime(), nullable=True)
    )
    op.execute("UPDATE service_product SET effective_time = '2022-11-01T00:00:00.000Z'")
    op.alter_column("service_product", "effective_time", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_product", "effective_time")
    # ### end Alembic commands ###
