"""empty message

Revision ID: b3ab67e4f408
Revises: 22f012f43711
Create Date: 2022-12-07 16:47:59.695818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3ab67e4f408'
down_revision = '22f012f43711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_order',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ecpay_merchant_trade_no', sa.String(length=20), nullable=False),
    sa.Column('ecpay_payment_result', sa.JSON(), nullable=True),
    sa.Column('ecpay_order_dict', sa.JSON(), nullable=True),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('care_product_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('payment_amount', sa.Numeric(), nullable=True),
    sa.Column('invoice_email_address', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('airtable_reference', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_product_financial_order'))
    )
    op.create_index(op.f('ix_esen_product_financial_order_create_time'), 'financial_order', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_product_financial_order_data_alias'), 'financial_order', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_product_financial_order_reference'), 'financial_order', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_product_financial_order_update_time'), 'financial_order', ['update_time'], unique=False)
    op.create_table('care_product_image',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('care_product_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('src', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['care_product_reference'], ['care_product.reference'], name=op.f('fk_esen_product_care_product_image_care_product_reference_care_product')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_product_care_product_image'))
    )
    op.create_index(op.f('ix_esen_product_care_product_image_care_product_reference'), 'care_product_image', ['care_product_reference'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_image_create_time'), 'care_product_image', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_image_data_alias'), 'care_product_image', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_image_reference'), 'care_product_image', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_image_update_time'), 'care_product_image', ['update_time'], unique=False)
    op.create_table('delivery_order',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('financial_order_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('raw_recipient_end_user_full_name', sa.String(length=32), nullable=False),
    sa.Column('raw_recipient_end_user_phone_number', sa.String(length=32), nullable=False),
    sa.Column('recipient_end_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('raw_served_end_user_full_name', sa.String(length=32), nullable=False),
    sa.Column('raw_served_end_user_phone_number', sa.String(length=32), nullable=False),
    sa.Column('served_end_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('delivery_address', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('airtable_reference', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['financial_order_reference'], ['financial_order.reference'], name=op.f('fk_esen_product_delivery_order_financial_order_reference_financial_order')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_product_delivery_order'))
    )
    op.create_index(op.f('ix_esen_product_delivery_order_create_time'), 'delivery_order', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_product_delivery_order_data_alias'), 'delivery_order', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_product_delivery_order_financial_order_reference'), 'delivery_order', ['financial_order_reference'], unique=False)
    op.create_index(op.f('ix_esen_product_delivery_order_reference'), 'delivery_order', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_product_delivery_order_update_time'), 'delivery_order', ['update_time'], unique=False)
    op.drop_index('ix_esen_product_order_create_time', table_name='order')
    op.drop_index('ix_esen_product_order_data_alias', table_name='order')
    op.drop_index('ix_esen_product_order_reference', table_name='order')
    op.drop_index('ix_esen_product_order_update_time', table_name='order')
    op.drop_table('order')
    op.add_column('care_product', sa.Column('delivery_order_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_product', 'delivery_order_count')
    op.create_table('order',
    sa.Column('reference', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_alias', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('care_product_reference', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipient_end_user_reference', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('served_end_user_reference', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('ecpay_merchant_trade_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ecpay_payment_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('organization_reference', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('airtable_reference', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('reference', name='pk_esen_product_order')
    )
    op.create_index('ix_esen_product_order_update_time', 'order', ['update_time'], unique=False)
    op.create_index('ix_esen_product_order_reference', 'order', ['reference'], unique=False)
    op.create_index('ix_esen_product_order_data_alias', 'order', ['data_alias'], unique=False)
    op.create_index('ix_esen_product_order_create_time', 'order', ['create_time'], unique=False)
    op.drop_index(op.f('ix_esen_product_delivery_order_update_time'), table_name='delivery_order')
    op.drop_index(op.f('ix_esen_product_delivery_order_reference'), table_name='delivery_order')
    op.drop_index(op.f('ix_esen_product_delivery_order_financial_order_reference'), table_name='delivery_order')
    op.drop_index(op.f('ix_esen_product_delivery_order_data_alias'), table_name='delivery_order')
    op.drop_index(op.f('ix_esen_product_delivery_order_create_time'), table_name='delivery_order')
    op.drop_table('delivery_order')
    op.drop_index(op.f('ix_esen_product_care_product_image_update_time'), table_name='care_product_image')
    op.drop_index(op.f('ix_esen_product_care_product_image_reference'), table_name='care_product_image')
    op.drop_index(op.f('ix_esen_product_care_product_image_data_alias'), table_name='care_product_image')
    op.drop_index(op.f('ix_esen_product_care_product_image_create_time'), table_name='care_product_image')
    op.drop_index(op.f('ix_esen_product_care_product_image_care_product_reference'), table_name='care_product_image')
    op.drop_table('care_product_image')
    op.drop_index(op.f('ix_esen_product_financial_order_update_time'), table_name='financial_order')
    op.drop_index(op.f('ix_esen_product_financial_order_reference'), table_name='financial_order')
    op.drop_index(op.f('ix_esen_product_financial_order_data_alias'), table_name='financial_order')
    op.drop_index(op.f('ix_esen_product_financial_order_create_time'), table_name='financial_order')
    op.drop_table('financial_order')
    # ### end Alembic commands ###
