"""empty message

Revision ID: 12ba2fb8d1ea
Revises: b3ab67e4f408
Create Date: 2022-12-09 12:18:07.040257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ba2fb8d1ea'
down_revision = 'b3ab67e4f408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_product', sa.Column('original_price_amount', sa.Numeric(), nullable=True))
    op.add_column('care_product', sa.Column('sale_price_amount', sa.Numeric(), nullable=True))
    op.add_column('care_product', sa.Column('display_specification_key', sa.String(length=1024), nullable=True))
    op.add_column('care_product', sa.Column('display_delivery_description_key', sa.String(length=1024), nullable=True))
    op.drop_constraint('fk_esen_product_delivery_order_financial_order_referenc_a6d0', 'delivery_order', type_='foreignkey')
    op.add_column('financial_order', sa.Column('paid_price_amount', sa.Numeric(), nullable=True))
    op.drop_column('financial_order', 'payment_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_order', sa.Column('payment_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('financial_order', 'paid_price_amount')
    op.create_foreign_key('fk_esen_product_delivery_order_financial_order_referenc_a6d0', 'delivery_order', 'financial_order', ['financial_order_reference'], ['reference'])
    op.drop_column('care_product', 'display_delivery_description_key')
    op.drop_column('care_product', 'display_specification_key')
    op.drop_column('care_product', 'sale_price_amount')
    op.drop_column('care_product', 'original_price_amount')
    # ### end Alembic commands ###
