"""empty message

Revision ID: 7df68d49cd2f
Revises: 04cecc0bc5bd
Create Date: 2022-12-16 11:41:46.737025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7df68d49cd2f'
down_revision = '04cecc0bc5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_product_promo_code',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('care_product_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('promo_code_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('discount_price_amount', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['care_product_reference'], ['care_product.reference'], name=op.f('fk_esen_product_care_product_promo_code_care_product_reference_care_product')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_product_care_product_promo_code'))
    )
    op.create_index(op.f('ix_esen_product_care_product_promo_code_care_product_reference'), 'care_product_promo_code', ['care_product_reference'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_promo_code_create_time'), 'care_product_promo_code', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_promo_code_data_alias'), 'care_product_promo_code', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_promo_code_reference'), 'care_product_promo_code', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_promo_code_update_time'), 'care_product_promo_code', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_product_care_product_promo_code_update_time'), table_name='care_product_promo_code')
    op.drop_index(op.f('ix_esen_product_care_product_promo_code_reference'), table_name='care_product_promo_code')
    op.drop_index(op.f('ix_esen_product_care_product_promo_code_data_alias'), table_name='care_product_promo_code')
    op.drop_index(op.f('ix_esen_product_care_product_promo_code_create_time'), table_name='care_product_promo_code')
    op.drop_index(op.f('ix_esen_product_care_product_promo_code_care_product_reference'), table_name='care_product_promo_code')
    op.drop_table('care_product_promo_code')
    # ### end Alembic commands ###
