"""empty message

Revision ID: 04cecc0bc5bd
Revises: a076226dae2c
Create Date: 2022-12-15 11:41:10.682053

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04cecc0bc5bd"
down_revision = "db5edff64cdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_order",
        "invoice_email_address",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    # ### end Alembic commands ###

    op.add_column(
        "delivery_order", sa.Column("is_in_store_pickup", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE delivery_order SET is_in_store_pickup = FALSE")
    op.alter_column("delivery_order", "is_in_store_pickup", nullable=False)

    op.add_column(
        "financial_order",
        sa.Column("is_created_by_organization", sa.Boolean(), nullable=True),
    )
    op.execute("UPDATE financial_order SET is_created_by_organization = FALSE")
    op.alter_column("financial_order", "is_created_by_organization", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("financial_order", "is_created_by_organization")
    op.drop_column("delivery_order", "is_in_store_pickup")
    op.alter_column(
        "financial_order",
        "invoice_email_address",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    # ### end Alembic commands ###
