"""empty message

Revision ID: 96c6a6f4a571
Revises: 7df68d49cd2f
Create Date: 2022-12-29 10:50:53.958688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c6a6f4a571'
down_revision = '7df68d49cd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_product_image', sa.Column('sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_product_image', 'sequence')
    # ### end Alembic commands ###
