"""empty message

Revision ID: 609331b48aab
Revises: 808313bfaab1
Create Date: 2022-11-30 16:19:51.500615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '609331b48aab'
down_revision = '808313bfaab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_product',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('display_sku_key', sa.String(length=128), nullable=False),
    sa.Column('display_description_key', sa.String(length=1024), nullable=True),
    sa.Column('non_covered_price_amount', sa.Numeric(), nullable=False),
    sa.Column('effective_time', sa.DateTime(), nullable=False),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_product_care_product'))
    )
    op.create_index(op.f('ix_esen_product_care_product_create_time'), 'care_product', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_data_alias'), 'care_product', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_organization_reference'), 'care_product', ['organization_reference'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_reference'), 'care_product', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_product_care_product_update_time'), 'care_product', ['update_time'], unique=False)
    op.create_table('order',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('care_product_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('recipient_end_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('payer_end_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('served_end_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_product_order'))
    )
    op.create_index(op.f('ix_esen_product_order_create_time'), 'order', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_product_order_data_alias'), 'order', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_product_order_reference'), 'order', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_product_order_update_time'), 'order', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_product_order_update_time'), table_name='order')
    op.drop_index(op.f('ix_esen_product_order_reference'), table_name='order')
    op.drop_index(op.f('ix_esen_product_order_data_alias'), table_name='order')
    op.drop_index(op.f('ix_esen_product_order_create_time'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_esen_product_care_product_update_time'), table_name='care_product')
    op.drop_index(op.f('ix_esen_product_care_product_reference'), table_name='care_product')
    op.drop_index(op.f('ix_esen_product_care_product_organization_reference'), table_name='care_product')
    op.drop_index(op.f('ix_esen_product_care_product_data_alias'), table_name='care_product')
    op.drop_index(op.f('ix_esen_product_care_product_create_time'), table_name='care_product')
    op.drop_table('care_product')
    # ### end Alembic commands ###
