"""empty message

Revision ID: 218a8e9e8d46
Revises: 1fee893b54fb
Create Date: 2022-12-13 16:02:06.665791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218a8e9e8d46'
down_revision = '1fee893b54fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_esen_marketing_end_user_care_product_referral_code_code'), 'end_user_care_product_referral_code', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_esen_marketing_end_user_care_product_referral_code_code'), 'end_user_care_product_referral_code', type_='unique')
    # ### end Alembic commands ###
