"""empty message

Revision ID: 9cbff9f1b4ba
Revises: b1245aff4430
Create Date: 2022-12-14 14:43:18.242918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cbff9f1b4ba'
down_revision = 'b1245aff4430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('program_name', sa.String(length=256), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('effective_time', sa.DateTime(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_marketing_promo_code'))
    )
    op.create_index(op.f('ix_esen_marketing_promo_code_create_time'), 'promo_code', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_marketing_promo_code_data_alias'), 'promo_code', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_marketing_promo_code_reference'), 'promo_code', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_marketing_promo_code_update_time'), 'promo_code', ['update_time'], unique=False)
    op.create_table('care_product_promo_code',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('care_product_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('discount_price_amount', sa.Numeric(), nullable=False),
    sa.Column('promo_code_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_reference'], ['promo_code.reference'], name=op.f('fk_esen_marketing_care_product_promo_code_promo_code_reference_promo_code')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_marketing_care_product_promo_code'))
    )
    op.create_index(op.f('ix_esen_marketing_care_product_promo_code_create_time'), 'care_product_promo_code', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_marketing_care_product_promo_code_data_alias'), 'care_product_promo_code', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_marketing_care_product_promo_code_promo_code_reference'), 'care_product_promo_code', ['promo_code_reference'], unique=False)
    op.create_index(op.f('ix_esen_marketing_care_product_promo_code_reference'), 'care_product_promo_code', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_marketing_care_product_promo_code_update_time'), 'care_product_promo_code', ['update_time'], unique=False)
    op.drop_index('ix_esen_marketing_coupon_create_time', table_name='cooperation_code')
    op.drop_index('ix_esen_marketing_coupon_data_alias', table_name='cooperation_code')
    op.drop_index('ix_esen_marketing_coupon_reference', table_name='cooperation_code')
    op.drop_index('ix_esen_marketing_coupon_update_time', table_name='cooperation_code')
    op.create_index(op.f('ix_esen_marketing_cooperation_code_create_time'), 'cooperation_code', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_marketing_cooperation_code_data_alias'), 'cooperation_code', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_marketing_cooperation_code_reference'), 'cooperation_code', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_marketing_cooperation_code_update_time'), 'cooperation_code', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_marketing_cooperation_code_update_time'), table_name='cooperation_code')
    op.drop_index(op.f('ix_esen_marketing_cooperation_code_reference'), table_name='cooperation_code')
    op.drop_index(op.f('ix_esen_marketing_cooperation_code_data_alias'), table_name='cooperation_code')
    op.drop_index(op.f('ix_esen_marketing_cooperation_code_create_time'), table_name='cooperation_code')
    op.create_index('ix_esen_marketing_coupon_update_time', 'cooperation_code', ['update_time'], unique=False)
    op.create_index('ix_esen_marketing_coupon_reference', 'cooperation_code', ['reference'], unique=False)
    op.create_index('ix_esen_marketing_coupon_data_alias', 'cooperation_code', ['data_alias'], unique=False)
    op.create_index('ix_esen_marketing_coupon_create_time', 'cooperation_code', ['create_time'], unique=False)
    op.drop_index(op.f('ix_esen_marketing_care_product_promo_code_update_time'), table_name='care_product_promo_code')
    op.drop_index(op.f('ix_esen_marketing_care_product_promo_code_reference'), table_name='care_product_promo_code')
    op.drop_index(op.f('ix_esen_marketing_care_product_promo_code_promo_code_reference'), table_name='care_product_promo_code')
    op.drop_index(op.f('ix_esen_marketing_care_product_promo_code_data_alias'), table_name='care_product_promo_code')
    op.drop_index(op.f('ix_esen_marketing_care_product_promo_code_create_time'), table_name='care_product_promo_code')
    op.drop_table('care_product_promo_code')
    op.drop_index(op.f('ix_esen_marketing_promo_code_update_time'), table_name='promo_code')
    op.drop_index(op.f('ix_esen_marketing_promo_code_reference'), table_name='promo_code')
    op.drop_index(op.f('ix_esen_marketing_promo_code_data_alias'), table_name='promo_code')
    op.drop_index(op.f('ix_esen_marketing_promo_code_create_time'), table_name='promo_code')
    op.drop_table('promo_code')
    # ### end Alembic commands ###
