"""empty message

Revision ID: 220509394d2b
Revises: a936a26ebecd
Create Date: 2022-12-16 11:32:05.875978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '220509394d2b'
down_revision = 'a936a26ebecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_esen_marketing_care_product_promo_code_create_time', table_name='care_product_promo_code')
    op.drop_index('ix_esen_marketing_care_product_promo_code_data_alias', table_name='care_product_promo_code')
    op.drop_index('ix_esen_marketing_care_product_promo_code_promo_code_reference', table_name='care_product_promo_code')
    op.drop_index('ix_esen_marketing_care_product_promo_code_reference', table_name='care_product_promo_code')
    op.drop_index('ix_esen_marketing_care_product_promo_code_update_time', table_name='care_product_promo_code')
    op.drop_table('care_product_promo_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_product_promo_code',
    sa.Column('reference', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_alias', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('care_product_reference', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('discount_price_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('promo_code_reference', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['promo_code_reference'], ['promo_code.reference'], name='fk_esen_marketing_care_product_promo_code_promo_code_re_d2ce'),
    sa.PrimaryKeyConstraint('reference', name='pk_esen_marketing_care_product_promo_code')
    )
    op.create_index('ix_esen_marketing_care_product_promo_code_update_time', 'care_product_promo_code', ['update_time'], unique=False)
    op.create_index('ix_esen_marketing_care_product_promo_code_reference', 'care_product_promo_code', ['reference'], unique=False)
    op.create_index('ix_esen_marketing_care_product_promo_code_promo_code_reference', 'care_product_promo_code', ['promo_code_reference'], unique=False)
    op.create_index('ix_esen_marketing_care_product_promo_code_data_alias', 'care_product_promo_code', ['data_alias'], unique=False)
    op.create_index('ix_esen_marketing_care_product_promo_code_create_time', 'care_product_promo_code', ['create_time'], unique=False)
    # ### end Alembic commands ###
