"""empty message

Revision ID: 4577ac1398f4
Revises: 06c25a572383
Create Date: 2022-11-21 15:33:17.922028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4577ac1398f4'
down_revision = '06c25a572383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_case',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('subject_end_user_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('assignee_internal_user_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ecpay_order_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('onboard_time', sa.DateTime(), nullable=True),
    sa.Column('effective_time', sa.DateTime(), nullable=True),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('care_plan', sa.Text(), nullable=True),
    sa.Column('closing_summary', sa.Text(), nullable=True),
    sa.Column('total_appointment_inventory_count_for_doctor', sa.Integer(), nullable=False),
    sa.Column('allocated_appointment_inventory_count_for_doctor', sa.Integer(), nullable=False),
    sa.Column('total_appointment_inventory_count_for_care_manager', sa.Integer(), nullable=False),
    sa.Column('allocated_appointment_inventory_count_for_care_manager', sa.Integer(), nullable=False),
    sa.Column('care_airtable_reference', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_emr_care_case'))
    )
    op.create_index(op.f('ix_esen_emr_care_case_create_time'), 'care_case', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_emr_care_case_data_alias'), 'care_case', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_emr_care_case_reference'), 'care_case', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_care_case_update_time'), 'care_case', ['update_time'], unique=False)
    op.create_table('care_case_review',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('care_case_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('care_manager_private_note', sa.Text(), nullable=True),
    sa.Column('display_subjective', sa.Text(), nullable=True),
    sa.Column('display_objective', sa.Text(), nullable=True),
    sa.Column('display_assessment', sa.Text(), nullable=True),
    sa.Column('display_plan', sa.Text(), nullable=True),
    sa.Column('care_airtable_reference', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['care_case_reference'], ['care_case.reference'], name=op.f('fk_esen_emr_care_case_review_care_case_reference_care_case')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_emr_care_case_review'))
    )
    op.create_index(op.f('ix_esen_emr_care_case_review_care_case_reference'), 'care_case_review', ['care_case_reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_care_case_review_create_time'), 'care_case_review', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_emr_care_case_review_data_alias'), 'care_case_review', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_emr_care_case_review_reference'), 'care_case_review', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_care_case_review_update_time'), 'care_case_review', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_emr_care_case_review_update_time'), table_name='care_case_review')
    op.drop_index(op.f('ix_esen_emr_care_case_review_reference'), table_name='care_case_review')
    op.drop_index(op.f('ix_esen_emr_care_case_review_data_alias'), table_name='care_case_review')
    op.drop_index(op.f('ix_esen_emr_care_case_review_create_time'), table_name='care_case_review')
    op.drop_index(op.f('ix_esen_emr_care_case_review_care_case_reference'), table_name='care_case_review')
    op.drop_table('care_case_review')
    op.drop_index(op.f('ix_esen_emr_care_case_update_time'), table_name='care_case')
    op.drop_index(op.f('ix_esen_emr_care_case_reference'), table_name='care_case')
    op.drop_index(op.f('ix_esen_emr_care_case_data_alias'), table_name='care_case')
    op.drop_index(op.f('ix_esen_emr_care_case_create_time'), table_name='care_case')
    op.drop_table('care_case')
    # ### end Alembic commands ###
