"""empty message

Revision ID: 06c25a572383
Revises: f34fcd470da3
Create Date: 2022-10-19 13:09:42.926061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06c25a572383'
down_revision = 'f34fcd470da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_group',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_emr_file_group'))
    )
    op.create_index(op.f('ix_esen_emr_file_group_create_time'), 'file_group', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_emr_file_group_data_alias'), 'file_group', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_emr_file_group_reference'), 'file_group', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_file_group_update_time'), 'file_group', ['update_time'], unique=False)
    op.create_table('examination_report',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('end_user_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_group_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['file_group_reference'], ['file_group.reference'], name=op.f('fk_esen_emr_examination_report_file_group_reference_file_group')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_emr_examination_report'))
    )
    op.create_index(op.f('ix_esen_emr_examination_report_create_time'), 'examination_report', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_emr_examination_report_data_alias'), 'examination_report', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_emr_examination_report_file_group_reference'), 'examination_report', ['file_group_reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_examination_report_reference'), 'examination_report', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_examination_report_update_time'), 'examination_report', ['update_time'], unique=False)
    op.create_table('file',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('file_group_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('raw_name', sa.String(length=256), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('size_in_byte', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_group_reference'], ['file_group.reference'], name=op.f('fk_esen_emr_file_file_group_reference_file_group')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_emr_file'))
    )
    op.create_index(op.f('ix_esen_emr_file_create_time'), 'file', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_emr_file_data_alias'), 'file', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_emr_file_file_group_reference'), 'file', ['file_group_reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_file_reference'), 'file', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_file_update_time'), 'file', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_emr_file_update_time'), table_name='file')
    op.drop_index(op.f('ix_esen_emr_file_reference'), table_name='file')
    op.drop_index(op.f('ix_esen_emr_file_file_group_reference'), table_name='file')
    op.drop_index(op.f('ix_esen_emr_file_data_alias'), table_name='file')
    op.drop_index(op.f('ix_esen_emr_file_create_time'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_esen_emr_examination_report_update_time'), table_name='examination_report')
    op.drop_index(op.f('ix_esen_emr_examination_report_reference'), table_name='examination_report')
    op.drop_index(op.f('ix_esen_emr_examination_report_file_group_reference'), table_name='examination_report')
    op.drop_index(op.f('ix_esen_emr_examination_report_data_alias'), table_name='examination_report')
    op.drop_index(op.f('ix_esen_emr_examination_report_create_time'), table_name='examination_report')
    op.drop_table('examination_report')
    op.drop_index(op.f('ix_esen_emr_file_group_update_time'), table_name='file_group')
    op.drop_index(op.f('ix_esen_emr_file_group_reference'), table_name='file_group')
    op.drop_index(op.f('ix_esen_emr_file_group_data_alias'), table_name='file_group')
    op.drop_index(op.f('ix_esen_emr_file_group_create_time'), table_name='file_group')
    op.drop_table('file_group')
    # ### end Alembic commands ###
