"""empty message

Revision ID: f34fcd470da3
Revises: 
Create Date: 2022-10-17 18:30:02.771576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f34fcd470da3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('end_user_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('appointment_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_emr_visit'))
    )
    op.create_index(op.f('ix_esen_emr_visit_create_time'), 'visit', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_emr_visit_data_alias'), 'visit', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_emr_visit_reference'), 'visit', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_emr_visit_update_time'), 'visit', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_emr_visit_update_time'), table_name='visit')
    op.drop_index(op.f('ix_esen_emr_visit_reference'), table_name='visit')
    op.drop_index(op.f('ix_esen_emr_visit_data_alias'), table_name='visit')
    op.drop_index(op.f('ix_esen_emr_visit_create_time'), table_name='visit')
    op.drop_table('visit')
    # ### end Alembic commands ###
