project:
  name: &project-name product-financial-order-synchronizer

image:
  repository: ${REPOSITORY_NAME}/${IMAGE_NAME}
  tag: $RELEASE_IMAGE_TAG

pod:
  priorityClassName: low-priority
  envs:
    - name: ENV
      value: production
    - name: DATABASE_URL
      value: $DATABASE_URL_PRODUCTION
    - name: SCHEMA_NAME
      value: esen_product
    - name: AMQP_URL
      value: $AMQP_URL_PRODUCTION
    - name: ECPAY_MERCHANT_ID
      value: "$ECPAY_MERCHANT_ID"
    - name: ECPAY_HASH_KEY
      value: "$ECPAY_HASH_KEY"
    - name: ECPAY_HASH_IV
      value: "$ECPAY_HASH_IV"
    - name: AIRTABLE_API_KEY
      value: $AIRTABLE_API_KEY
    - name: AIRTABLE_API_KEY_EDITOR
      value: $AIRTABLE_API_KEY_EDITOR

cronjob:
  schedule: "*/10 * * * *"
