project:
  name: &project-name emr-web-server

image:
  repository: ${REPOSITORY_NAME}/${IMAGE_NAME}
  tag: $RELEASE_IMAGE_TAG

pod:
  labels:
    env: "staging"
    cluster: "esen-cloud-staging"
  resources:
    requests:
      cpu: 100m
    limits:
      cpu: 100m
  priorityClassName: mid-priority
  envs:
    - name: ENV
      value: staging
    - name: DATABASE_URL
      value: $DATABASE_URL_STAGING
    - name: SCHEMA_NAME
      value: esen_emr
    - name: STORAGE_ENGINE_CREDENTIALS
      value: $STORAGE_ENGINE_CREDENTIALS
    - name: AIRTABLE_API_KEY
      value: $AIRTABLE_API_KEY
    - name: SERVICE_ACCESS_TOKEN
      value: $EMR_SERVICE_ACCESS_TOKEN
  port: &pod-port 9005

healthz:
  path: /
  initialDelay: 300
  period: 600
  timeout: 10
  success: 1
  failure: 3

autoScaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

ingress:
  issuer: issuer-letsencrypt-staging
  tls:
    - hosts:
        - emr.stg-cloud.esenmedical.com
      secretName: secret-stg-cloud-esenmedical-com-tls
  rules:
    - host: emr.stg-cloud.esenmedical.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *project-name
                port:
                  number: *pod-port
