"""empty message

Revision ID: 8991e3649500
Revises: b68f4c009540
Create Date: 2022-10-27 13:54:57.112050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8991e3649500'
down_revision = 'b68f4c009540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('coupon_code', sa.String(length=32), nullable=True))
    op.add_column('appointment', sa.Column('airtable_reference', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'airtable_reference')
    op.drop_column('appointment', 'coupon_code')
    # ### end Alembic commands ###
