"""empty message

Revision ID: b68f4c009540
Revises: 
Create Date: 2022-10-26 13:54:59.917980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b68f4c009540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('service_product_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('end_user_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('_evaluated_time_slot_start_time', sa.DateTime(), nullable=False),
    sa.Column('_evaluated_time_slot_end_time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_appointment'))
    )
    op.create_index(op.f('ix_esen_scheduling_appointment_create_time'), 'appointment', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_appointment_data_alias'), 'appointment', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_appointment_end_user_reference'), 'appointment', ['end_user_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_appointment_organization_reference'), 'appointment', ['organization_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_appointment_reference'), 'appointment', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_appointment_service_product_reference'), 'appointment', ['service_product_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_appointment_update_time'), 'appointment', ['update_time'], unique=False)
    op.create_table('internal_user_time_slot_inventory',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('_version', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('_time_slot_start_time', sa.DateTime(), nullable=False),
    sa.Column('_time_slot_end_time', sa.DateTime(), nullable=False),
    sa.Column('total_inventory', sa.Integer(), nullable=False),
    sa.Column('total_allocated', sa.Integer(), nullable=False),
    sa.Column('internal_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_internal_user_time_slot_inventory'))
    )
    op.create_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_create_time'), 'internal_user_time_slot_inventory', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_data_alias'), 'internal_user_time_slot_inventory', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_internal_user_reference'), 'internal_user_time_slot_inventory', ['internal_user_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_organization_reference'), 'internal_user_time_slot_inventory', ['organization_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_reference'), 'internal_user_time_slot_inventory', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_update_time'), 'internal_user_time_slot_inventory', ['update_time'], unique=False)
    op.create_table('room_time_slot_inventory',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('_version', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('_time_slot_start_time', sa.DateTime(), nullable=False),
    sa.Column('_time_slot_end_time', sa.DateTime(), nullable=False),
    sa.Column('total_inventory', sa.Integer(), nullable=False),
    sa.Column('total_allocated', sa.Integer(), nullable=False),
    sa.Column('room_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_room_time_slot_inventory'))
    )
    op.create_index(op.f('ix_esen_scheduling_room_time_slot_inventory_create_time'), 'room_time_slot_inventory', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_time_slot_inventory_data_alias'), 'room_time_slot_inventory', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_time_slot_inventory_organization_reference'), 'room_time_slot_inventory', ['organization_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_time_slot_inventory_reference'), 'room_time_slot_inventory', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_time_slot_inventory_room_reference'), 'room_time_slot_inventory', ['room_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_time_slot_inventory_update_time'), 'room_time_slot_inventory', ['update_time'], unique=False)
    op.create_table('internal_user_appointment_time_slot',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('_time_slot_start_time', sa.DateTime(), nullable=False),
    sa.Column('_time_slot_end_time', sa.DateTime(), nullable=False),
    sa.Column('appointment_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('allocated_inventory', sa.Integer(), nullable=False),
    sa.Column('internal_user_time_slot_inventory_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('internal_user_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_reference'], ['appointment.reference'], name=op.f('fk_esen_scheduling_internal_user_appointment_time_slot_appointment_reference_appointment')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_internal_user_appointment_time_slot'))
    )
    op.create_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_reference'), 'internal_user_appointment_time_slot', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_data_alias'), 'internal_user_appointment_time_slot', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_internal_user_time_slot_inventory_reference'), 'internal_user_appointment_time_slot', ['internal_user_time_slot_inventory_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_appointment_reference'), 'internal_user_appointment_time_slot', ['appointment_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_update_time'), 'internal_user_appointment_time_slot', ['update_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_create_time'), 'internal_user_appointment_time_slot', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_internal_user_reference'), 'internal_user_appointment_time_slot', ['internal_user_reference'], unique=False)
    op.create_table('room_appointment_time_slot',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('_time_slot_start_time', sa.DateTime(), nullable=False),
    sa.Column('_time_slot_end_time', sa.DateTime(), nullable=False),
    sa.Column('appointment_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('allocated_inventory', sa.Integer(), nullable=False),
    sa.Column('room_time_slot_inventory_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('room_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_reference'], ['appointment.reference'], name=op.f('fk_esen_scheduling_room_appointment_time_slot_appointment_reference_appointment')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_room_appointment_time_slot'))
    )
    op.create_index(op.f('ix_esen_scheduling_room_appointment_time_slot_appointment_reference'), 'room_appointment_time_slot', ['appointment_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_appointment_time_slot_create_time'), 'room_appointment_time_slot', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_appointment_time_slot_data_alias'), 'room_appointment_time_slot', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_appointment_time_slot_reference'), 'room_appointment_time_slot', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_appointment_time_slot_room_reference'), 'room_appointment_time_slot', ['room_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_appointment_time_slot_room_time_slot_inventory_reference'), 'room_appointment_time_slot', ['room_time_slot_inventory_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_room_appointment_time_slot_update_time'), 'room_appointment_time_slot', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_scheduling_room_appointment_time_slot_update_time'), table_name='room_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_room_appointment_time_slot_room_time_slot_inventory_reference'), table_name='room_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_room_appointment_time_slot_room_reference'), table_name='room_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_room_appointment_time_slot_reference'), table_name='room_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_room_appointment_time_slot_data_alias'), table_name='room_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_room_appointment_time_slot_create_time'), table_name='room_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_room_appointment_time_slot_appointment_reference'), table_name='room_appointment_time_slot')
    op.drop_table('room_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_internal_user_reference'), table_name='internal_user_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_create_time'), table_name='internal_user_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_update_time'), table_name='internal_user_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_appointment_reference'), table_name='internal_user_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_internal_user_time_slot_inventory_reference'), table_name='internal_user_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_data_alias'), table_name='internal_user_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_appointment_time_slot_reference'), table_name='internal_user_appointment_time_slot')
    op.drop_table('internal_user_appointment_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_room_time_slot_inventory_update_time'), table_name='room_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_room_time_slot_inventory_room_reference'), table_name='room_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_room_time_slot_inventory_reference'), table_name='room_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_room_time_slot_inventory_organization_reference'), table_name='room_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_room_time_slot_inventory_data_alias'), table_name='room_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_room_time_slot_inventory_create_time'), table_name='room_time_slot_inventory')
    op.drop_table('room_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_update_time'), table_name='internal_user_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_reference'), table_name='internal_user_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_organization_reference'), table_name='internal_user_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_internal_user_reference'), table_name='internal_user_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_data_alias'), table_name='internal_user_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_internal_user_time_slot_inventory_create_time'), table_name='internal_user_time_slot_inventory')
    op.drop_table('internal_user_time_slot_inventory')
    op.drop_index(op.f('ix_esen_scheduling_appointment_update_time'), table_name='appointment')
    op.drop_index(op.f('ix_esen_scheduling_appointment_service_product_reference'), table_name='appointment')
    op.drop_index(op.f('ix_esen_scheduling_appointment_reference'), table_name='appointment')
    op.drop_index(op.f('ix_esen_scheduling_appointment_organization_reference'), table_name='appointment')
    op.drop_index(op.f('ix_esen_scheduling_appointment_end_user_reference'), table_name='appointment')
    op.drop_index(op.f('ix_esen_scheduling_appointment_data_alias'), table_name='appointment')
    op.drop_index(op.f('ix_esen_scheduling_appointment_create_time'), table_name='appointment')
    op.drop_table('appointment')
    # ### end Alembic commands ###
