"""empty message

Revision ID: 0c86772c0be7
Revises: 0154b43ee2b5
Create Date: 2023-01-10 12:38:11.756003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c86772c0be7'
down_revision = '0154b43ee2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('min_date', sa.Date(), nullable=False),
    sa.Column('max_date', sa.Date(), nullable=False),
    sa.Column('timezone_offset_in_minutes', sa.Integer(), nullable=False),
    sa.Column('last_publish_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_schedule'))
    )
    op.create_index(op.f('ix_esen_scheduling_schedule_create_time'), 'schedule', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_data_alias'), 'schedule', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_reference'), 'schedule', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_update_time'), 'schedule', ['update_time'], unique=False)
    op.create_table('schedule_date',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('schedule_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_reference'], ['schedule.reference'], name=op.f('fk_esen_scheduling_schedule_date_schedule_reference_schedule')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_schedule_date'))
    )
    op.create_index(op.f('ix_esen_scheduling_schedule_date_create_time'), 'schedule_date', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_data_alias'), 'schedule_date', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_reference'), 'schedule_date', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_reference'), 'schedule_date', ['schedule_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_update_time'), 'schedule_date', ['update_time'], unique=False)
    op.create_table('schedule_date_schedule_time_slot',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('schedule_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schedule_date_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schedule_time_slot_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('override_schedule_time_slot_start_time', sa.Time(), nullable=True),
    sa.Column('override_schedule_time_slot_end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_reference'], ['schedule.reference'], name=op.f('fk_esen_scheduling_schedule_date_schedule_time_slot_schedule_reference_schedule')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_schedule_date_schedule_time_slot'))
    )
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_create_time'), 'schedule_date_schedule_time_slot', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_data_alias'), 'schedule_date_schedule_time_slot', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_reference'), 'schedule_date_schedule_time_slot', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_schedule_reference'), 'schedule_date_schedule_time_slot', ['schedule_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_update_time'), 'schedule_date_schedule_time_slot', ['update_time'], unique=False)
    op.create_table('schedule_time_slot',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('schedule_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('weekday_indices', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['schedule_reference'], ['schedule.reference'], name=op.f('fk_esen_scheduling_schedule_time_slot_schedule_reference_schedule')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_schedule_time_slot'))
    )
    op.create_index(op.f('ix_esen_scheduling_schedule_time_slot_create_time'), 'schedule_time_slot', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_time_slot_data_alias'), 'schedule_time_slot', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_time_slot_reference'), 'schedule_time_slot', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_time_slot_schedule_reference'), 'schedule_time_slot', ['schedule_reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_time_slot_update_time'), 'schedule_time_slot', ['update_time'], unique=False)
    op.create_table('schedule_date_schedule_time_slot_internal_user',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('schedule_date_schedule_time_slot_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('internal_user_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_date_schedule_time_slot_reference'], ['schedule_date_schedule_time_slot.reference'], name=op.f('fk_esen_scheduling_schedule_date_schedule_time_slot_internal_user_schedule_date_schedule_time_slot_reference_schedule_date_schedule_time_slot')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_scheduling_schedule_date_schedule_time_slot_internal_user'))
    )
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_create_time'), 'schedule_date_schedule_time_slot_internal_user', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_data_alias'), 'schedule_date_schedule_time_slot_internal_user', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_update_time'), 'schedule_date_schedule_time_slot_internal_user', ['update_time'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_reference'), 'schedule_date_schedule_time_slot_internal_user', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_schedule_date_schedule_time_slot_reference'), 'schedule_date_schedule_time_slot_internal_user', ['schedule_date_schedule_time_slot_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_schedule_date_schedule_time_slot_reference'), table_name='schedule_date_schedule_time_slot_internal_user')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_reference'), table_name='schedule_date_schedule_time_slot_internal_user')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_update_time'), table_name='schedule_date_schedule_time_slot_internal_user')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_data_alias'), table_name='schedule_date_schedule_time_slot_internal_user')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_internal_user_create_time'), table_name='schedule_date_schedule_time_slot_internal_user')
    op.drop_table('schedule_date_schedule_time_slot_internal_user')
    op.drop_index(op.f('ix_esen_scheduling_schedule_time_slot_update_time'), table_name='schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_time_slot_schedule_reference'), table_name='schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_time_slot_reference'), table_name='schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_time_slot_data_alias'), table_name='schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_time_slot_create_time'), table_name='schedule_time_slot')
    op.drop_table('schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_update_time'), table_name='schedule_date_schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_schedule_reference'), table_name='schedule_date_schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_reference'), table_name='schedule_date_schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_data_alias'), table_name='schedule_date_schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_time_slot_create_time'), table_name='schedule_date_schedule_time_slot')
    op.drop_table('schedule_date_schedule_time_slot')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_update_time'), table_name='schedule_date')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_schedule_reference'), table_name='schedule_date')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_reference'), table_name='schedule_date')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_data_alias'), table_name='schedule_date')
    op.drop_index(op.f('ix_esen_scheduling_schedule_date_create_time'), table_name='schedule_date')
    op.drop_table('schedule_date')
    op.drop_index(op.f('ix_esen_scheduling_schedule_update_time'), table_name='schedule')
    op.drop_index(op.f('ix_esen_scheduling_schedule_reference'), table_name='schedule')
    op.drop_index(op.f('ix_esen_scheduling_schedule_data_alias'), table_name='schedule')
    op.drop_index(op.f('ix_esen_scheduling_schedule_create_time'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
