"""empty message

Revision ID: 6158058da083
Revises: 3b24f5cbea89
Create Date: 2022-11-24 18:50:01.070887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6158058da083'
down_revision = '3b24f5cbea89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('display_sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'display_sequence')
    # ### end Alembic commands ###
