"""empty message

Revision ID: b46af5226609
Revises: d13e7118b074
Create Date: 2022-10-17 12:35:53.570729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b46af5226609'
down_revision = 'd13e7118b074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurer',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('official_key', sa.String(length=128), nullable=True),
    sa.Column('display_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_insurer'))
    )
    op.create_index(op.f('ix_esen_iam_insurer_create_time'), 'insurer', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_insurer_data_alias'), 'insurer', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_insurer_reference'), 'insurer', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_insurer_update_time'), 'insurer', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_iam_insurer_update_time'), table_name='insurer')
    op.drop_index(op.f('ix_esen_iam_insurer_reference'), table_name='insurer')
    op.drop_index(op.f('ix_esen_iam_insurer_data_alias'), table_name='insurer')
    op.drop_index(op.f('ix_esen_iam_insurer_create_time'), table_name='insurer')
    op.drop_table('insurer')
    # ### end Alembic commands ###
