"""empty message

Revision ID: 83d2735716bc
Revises: 89064e59a95d
Create Date: 2022-12-01 16:23:22.687027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d2735716bc'
down_revision = '89064e59a95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_user', sa.Column('is_created_by_internal_user', sa.Boolean(), nullable=True))
    op.add_column('end_user', sa.Column('is_created_by_service', sa.Boolean(), nullable=True))
    op.drop_column('end_user', 'is_manually_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_user', sa.Column('is_manually_created', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('end_user', 'is_created_by_service')
    op.drop_column('end_user', 'is_created_by_internal_user')
    # ### end Alembic commands ###
