"""empty message

Revision ID: 7dd7ade74480
Revises: aeab01f3a98f
Create Date: 2022-11-10 16:17:21.121925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dd7ade74480'
down_revision = 'aeab01f3a98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_internal_user',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('internal_user_reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('position', sa.String(length=32), nullable=False),
    sa.Column('employment_state', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['internal_user_reference'], ['internal_user.reference'], name=op.f('fk_esen_iam_organization_internal_user_internal_user_reference_internal_user')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_organization_internal_user'))
    )
    op.create_index(op.f('ix_esen_iam_organization_internal_user_create_time'), 'organization_internal_user', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_internal_user_data_alias'), 'organization_internal_user', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_internal_user_internal_user_reference'), 'organization_internal_user', ['internal_user_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_internal_user_reference'), 'organization_internal_user', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_internal_user_update_time'), 'organization_internal_user', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_iam_organization_internal_user_update_time'), table_name='organization_internal_user')
    op.drop_index(op.f('ix_esen_iam_organization_internal_user_reference'), table_name='organization_internal_user')
    op.drop_index(op.f('ix_esen_iam_organization_internal_user_internal_user_reference'), table_name='organization_internal_user')
    op.drop_index(op.f('ix_esen_iam_organization_internal_user_data_alias'), table_name='organization_internal_user')
    op.drop_index(op.f('ix_esen_iam_organization_internal_user_create_time'), table_name='organization_internal_user')
    op.drop_table('organization_internal_user')
    # ### end Alembic commands ###
