"""empty message

Revision ID: d13e7118b074
Revises: 
Create Date: 2022-10-13 11:22:38.714178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd13e7118b074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('end_user',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email_address', sa.String(length=256), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('blood_type', sa.String(length=32), nullable=True),
    sa.Column('correspondence_address', sa.String(length=1024), nullable=True),
    sa.Column('tw_identity_card_number', sa.String(length=32), nullable=True),
    sa.Column('passport_number', sa.String(length=128), nullable=True),
    sa.Column('emergency_contact_first_name', sa.String(length=128), nullable=True),
    sa.Column('emergency_contact_last_name', sa.String(length=128), nullable=True),
    sa.Column('emergency_contact_relationship_type', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact_phone_number', sa.String(length=32), nullable=True),
    sa.Column('airtable_record_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_end_user'))
    )
    op.create_index(op.f('ix_esen_iam_end_user_create_time'), 'end_user', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_data_alias'), 'end_user', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_reference'), 'end_user', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_update_time'), 'end_user', ['update_time'], unique=False)
    op.create_table('internal_user',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('email_address', sa.String(length=256), nullable=False),
    sa.Column('password_salt', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('avatar_src', sa.String(length=1024), nullable=True),
    sa.Column('education', sa.String(length=128), nullable=True),
    sa.Column('biography', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_internal_user'))
    )
    op.create_index(op.f('ix_esen_iam_internal_user_create_time'), 'internal_user', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_data_alias'), 'internal_user', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_reference'), 'internal_user', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_update_time'), 'internal_user', ['update_time'], unique=False)
    op.create_table('organization',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('official_name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('branch_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('banner_src', sa.String(length=1024), nullable=True),
    sa.Column('correspondence_address', sa.String(length=256), nullable=True),
    sa.Column('parent_organization_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_organization_reference'], ['organization.reference'], name=op.f('fk_esen_iam_organization_parent_organization_reference_organization')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_organization'))
    )
    op.create_index(op.f('ix_esen_iam_organization_create_time'), 'organization', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_data_alias'), 'organization', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_parent_organization_reference'), 'organization', ['parent_organization_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_reference'), 'organization', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_update_time'), 'organization', ['update_time'], unique=False)
    op.create_table('otp_token',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('serial_number', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_otp_token'))
    )
    op.create_index(op.f('ix_esen_iam_otp_token_create_time'), 'otp_token', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_otp_token_data_alias'), 'otp_token', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_otp_token_expiration_time'), 'otp_token', ['expiration_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_otp_token_is_active'), 'otp_token', ['is_active'], unique=False)
    op.create_index(op.f('ix_esen_iam_otp_token_reference'), 'otp_token', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_otp_token_update_time'), 'otp_token', ['update_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_otp_token_value'), 'otp_token', ['value'], unique=False)
    op.create_table('permission',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('identifier_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_permission')),
    sa.UniqueConstraint('identifier_key', name=op.f('uq_esen_iam_permission_identifier_key'))
    )
    op.create_index(op.f('ix_esen_iam_permission_create_time'), 'permission', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_permission_data_alias'), 'permission', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_permission_reference'), 'permission', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_permission_update_time'), 'permission', ['update_time'], unique=False)
    op.create_table('end_user_access_token',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('end_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['end_user_reference'], ['end_user.reference'], name=op.f('fk_esen_iam_end_user_access_token_end_user_reference_end_user')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_end_user_access_token'))
    )
    op.create_index(op.f('ix_esen_iam_end_user_access_token_create_time'), 'end_user_access_token', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_access_token_data_alias'), 'end_user_access_token', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_access_token_end_user_reference'), 'end_user_access_token', ['end_user_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_access_token_expiration_time'), 'end_user_access_token', ['expiration_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_access_token_is_active'), 'end_user_access_token', ['is_active'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_access_token_reference'), 'end_user_access_token', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_access_token_update_time'), 'end_user_access_token', ['update_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_end_user_access_token_value'), 'end_user_access_token', ['value'], unique=False)
    op.create_table('internal_user_access_token',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('internal_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['internal_user_reference'], ['internal_user.reference'], name=op.f('fk_esen_iam_internal_user_access_token_internal_user_reference_internal_user')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_internal_user_access_token'))
    )
    op.create_index(op.f('ix_esen_iam_internal_user_access_token_create_time'), 'internal_user_access_token', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_access_token_data_alias'), 'internal_user_access_token', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_access_token_expiration_time'), 'internal_user_access_token', ['expiration_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_access_token_internal_user_reference'), 'internal_user_access_token', ['internal_user_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_access_token_is_active'), 'internal_user_access_token', ['is_active'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_access_token_reference'), 'internal_user_access_token', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_access_token_update_time'), 'internal_user_access_token', ['update_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_internal_user_access_token_value'), 'internal_user_access_token', ['value'], unique=False)
    op.create_table('organization_organization',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('upstream_organization_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('downstream_organization_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['downstream_organization_reference'], ['organization.reference'], name=op.f('fk_esen_iam_organization_organization_downstream_organization_reference_organization')),
    sa.ForeignKeyConstraint(['upstream_organization_reference'], ['organization.reference'], name=op.f('fk_esen_iam_organization_organization_upstream_organization_reference_organization')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_organization_organization'))
    )
    op.create_index(op.f('ix_esen_iam_organization_organization_create_time'), 'organization_organization', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_organization_data_alias'), 'organization_organization', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_organization_downstream_organization_reference'), 'organization_organization', ['downstream_organization_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_organization_reference'), 'organization_organization', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_organization_update_time'), 'organization_organization', ['update_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_organization_organization_upstream_organization_reference'), 'organization_organization', ['upstream_organization_reference'], unique=False)
    op.create_table('team',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['organization_reference'], ['organization.reference'], name=op.f('fk_esen_iam_team_organization_reference_organization')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_team'))
    )
    op.create_index(op.f('ix_esen_iam_team_create_time'), 'team', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_data_alias'), 'team', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_organization_reference'), 'team', ['organization_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_reference'), 'team', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_update_time'), 'team', ['update_time'], unique=False)
    op.create_table('team_internal_user',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('team_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('internal_user_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['internal_user_reference'], ['internal_user.reference'], name=op.f('fk_esen_iam_team_internal_user_internal_user_reference_internal_user')),
    sa.ForeignKeyConstraint(['team_reference'], ['team.reference'], name=op.f('fk_esen_iam_team_internal_user_team_reference_team')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_team_internal_user'))
    )
    op.create_index(op.f('ix_esen_iam_team_internal_user_create_time'), 'team_internal_user', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_internal_user_data_alias'), 'team_internal_user', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_internal_user_internal_user_reference'), 'team_internal_user', ['internal_user_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_internal_user_reference'), 'team_internal_user', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_internal_user_team_reference'), 'team_internal_user', ['team_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_internal_user_update_time'), 'team_internal_user', ['update_time'], unique=False)
    op.create_table('team_permission',
    sa.Column('reference', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_alias', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('team_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('permission_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_reference'], ['permission.reference'], name=op.f('fk_esen_iam_team_permission_permission_reference_permission')),
    sa.ForeignKeyConstraint(['team_reference'], ['team.reference'], name=op.f('fk_esen_iam_team_permission_team_reference_team')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_esen_iam_team_permission'))
    )
    op.create_index(op.f('ix_esen_iam_team_permission_create_time'), 'team_permission', ['create_time'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_permission_data_alias'), 'team_permission', ['data_alias'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_permission_permission_reference'), 'team_permission', ['permission_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_permission_reference'), 'team_permission', ['reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_permission_team_reference'), 'team_permission', ['team_reference'], unique=False)
    op.create_index(op.f('ix_esen_iam_team_permission_update_time'), 'team_permission', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esen_iam_team_permission_update_time'), table_name='team_permission')
    op.drop_index(op.f('ix_esen_iam_team_permission_team_reference'), table_name='team_permission')
    op.drop_index(op.f('ix_esen_iam_team_permission_reference'), table_name='team_permission')
    op.drop_index(op.f('ix_esen_iam_team_permission_permission_reference'), table_name='team_permission')
    op.drop_index(op.f('ix_esen_iam_team_permission_data_alias'), table_name='team_permission')
    op.drop_index(op.f('ix_esen_iam_team_permission_create_time'), table_name='team_permission')
    op.drop_table('team_permission')
    op.drop_index(op.f('ix_esen_iam_team_internal_user_update_time'), table_name='team_internal_user')
    op.drop_index(op.f('ix_esen_iam_team_internal_user_team_reference'), table_name='team_internal_user')
    op.drop_index(op.f('ix_esen_iam_team_internal_user_reference'), table_name='team_internal_user')
    op.drop_index(op.f('ix_esen_iam_team_internal_user_internal_user_reference'), table_name='team_internal_user')
    op.drop_index(op.f('ix_esen_iam_team_internal_user_data_alias'), table_name='team_internal_user')
    op.drop_index(op.f('ix_esen_iam_team_internal_user_create_time'), table_name='team_internal_user')
    op.drop_table('team_internal_user')
    op.drop_index(op.f('ix_esen_iam_team_update_time'), table_name='team')
    op.drop_index(op.f('ix_esen_iam_team_reference'), table_name='team')
    op.drop_index(op.f('ix_esen_iam_team_organization_reference'), table_name='team')
    op.drop_index(op.f('ix_esen_iam_team_data_alias'), table_name='team')
    op.drop_index(op.f('ix_esen_iam_team_create_time'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_esen_iam_organization_organization_upstream_organization_reference'), table_name='organization_organization')
    op.drop_index(op.f('ix_esen_iam_organization_organization_update_time'), table_name='organization_organization')
    op.drop_index(op.f('ix_esen_iam_organization_organization_reference'), table_name='organization_organization')
    op.drop_index(op.f('ix_esen_iam_organization_organization_downstream_organization_reference'), table_name='organization_organization')
    op.drop_index(op.f('ix_esen_iam_organization_organization_data_alias'), table_name='organization_organization')
    op.drop_index(op.f('ix_esen_iam_organization_organization_create_time'), table_name='organization_organization')
    op.drop_table('organization_organization')
    op.drop_index(op.f('ix_esen_iam_internal_user_access_token_value'), table_name='internal_user_access_token')
    op.drop_index(op.f('ix_esen_iam_internal_user_access_token_update_time'), table_name='internal_user_access_token')
    op.drop_index(op.f('ix_esen_iam_internal_user_access_token_reference'), table_name='internal_user_access_token')
    op.drop_index(op.f('ix_esen_iam_internal_user_access_token_is_active'), table_name='internal_user_access_token')
    op.drop_index(op.f('ix_esen_iam_internal_user_access_token_internal_user_reference'), table_name='internal_user_access_token')
    op.drop_index(op.f('ix_esen_iam_internal_user_access_token_expiration_time'), table_name='internal_user_access_token')
    op.drop_index(op.f('ix_esen_iam_internal_user_access_token_data_alias'), table_name='internal_user_access_token')
    op.drop_index(op.f('ix_esen_iam_internal_user_access_token_create_time'), table_name='internal_user_access_token')
    op.drop_table('internal_user_access_token')
    op.drop_index(op.f('ix_esen_iam_end_user_access_token_value'), table_name='end_user_access_token')
    op.drop_index(op.f('ix_esen_iam_end_user_access_token_update_time'), table_name='end_user_access_token')
    op.drop_index(op.f('ix_esen_iam_end_user_access_token_reference'), table_name='end_user_access_token')
    op.drop_index(op.f('ix_esen_iam_end_user_access_token_is_active'), table_name='end_user_access_token')
    op.drop_index(op.f('ix_esen_iam_end_user_access_token_expiration_time'), table_name='end_user_access_token')
    op.drop_index(op.f('ix_esen_iam_end_user_access_token_end_user_reference'), table_name='end_user_access_token')
    op.drop_index(op.f('ix_esen_iam_end_user_access_token_data_alias'), table_name='end_user_access_token')
    op.drop_index(op.f('ix_esen_iam_end_user_access_token_create_time'), table_name='end_user_access_token')
    op.drop_table('end_user_access_token')
    op.drop_index(op.f('ix_esen_iam_permission_update_time'), table_name='permission')
    op.drop_index(op.f('ix_esen_iam_permission_reference'), table_name='permission')
    op.drop_index(op.f('ix_esen_iam_permission_data_alias'), table_name='permission')
    op.drop_index(op.f('ix_esen_iam_permission_create_time'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_esen_iam_otp_token_value'), table_name='otp_token')
    op.drop_index(op.f('ix_esen_iam_otp_token_update_time'), table_name='otp_token')
    op.drop_index(op.f('ix_esen_iam_otp_token_reference'), table_name='otp_token')
    op.drop_index(op.f('ix_esen_iam_otp_token_is_active'), table_name='otp_token')
    op.drop_index(op.f('ix_esen_iam_otp_token_expiration_time'), table_name='otp_token')
    op.drop_index(op.f('ix_esen_iam_otp_token_data_alias'), table_name='otp_token')
    op.drop_index(op.f('ix_esen_iam_otp_token_create_time'), table_name='otp_token')
    op.drop_table('otp_token')
    op.drop_index(op.f('ix_esen_iam_organization_update_time'), table_name='organization')
    op.drop_index(op.f('ix_esen_iam_organization_reference'), table_name='organization')
    op.drop_index(op.f('ix_esen_iam_organization_parent_organization_reference'), table_name='organization')
    op.drop_index(op.f('ix_esen_iam_organization_data_alias'), table_name='organization')
    op.drop_index(op.f('ix_esen_iam_organization_create_time'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_esen_iam_internal_user_update_time'), table_name='internal_user')
    op.drop_index(op.f('ix_esen_iam_internal_user_reference'), table_name='internal_user')
    op.drop_index(op.f('ix_esen_iam_internal_user_data_alias'), table_name='internal_user')
    op.drop_index(op.f('ix_esen_iam_internal_user_create_time'), table_name='internal_user')
    op.drop_table('internal_user')
    op.drop_index(op.f('ix_esen_iam_end_user_update_time'), table_name='end_user')
    op.drop_index(op.f('ix_esen_iam_end_user_reference'), table_name='end_user')
    op.drop_index(op.f('ix_esen_iam_end_user_data_alias'), table_name='end_user')
    op.drop_index(op.f('ix_esen_iam_end_user_create_time'), table_name='end_user')
    op.drop_table('end_user')
    # ### end Alembic commands ###
