"""empty message

Revision ID: 0963c9b334c9
Revises: 0fdd259e7dcc
Create Date: 2022-10-20 14:04:33.853374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0963c9b334c9'
down_revision = '0fdd259e7dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_user', 'airtable_record_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_user', sa.Column('airtable_record_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
