"""empty message

Revision ID: 4b805287551b
Revises: 7dd7ade74480
Create Date: 2022-11-17 13:50:31.589998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b805287551b'
down_revision = '7dd7ade74480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_internal_user', sa.Column('last_resign_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_internal_user', 'last_resign_time')
    # ### end Alembic commands ###
