"""empty message

Revision ID: d9b4aff06a29
Revises: 876b5d2747ba
Create Date: 2022-10-21 12:08:31.620920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b4aff06a29'
down_revision = '876b5d2747ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_user', sa.Column('airtable_reference', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_user', 'airtable_reference')
    # ### end Alembic commands ###
