"""empty message

Revision ID: 56923331ef8a
Revises: 83d2735716bc
Create Date: 2022-12-08 16:15:37.094293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56923331ef8a'
down_revision = '83d2735716bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_user', sa.Column('is_guest', sa.Boolean(), nullable=True))
    op.drop_column('end_user', 'is_created_by_service')
    op.drop_column('end_user', 'is_created_by_internal_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_user', sa.Column('is_created_by_internal_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('end_user', sa.Column('is_created_by_service', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('end_user', 'is_guest')
    # ### end Alembic commands ###
