"""empty message

Revision ID: 89064e59a95d
Revises: 6158058da083
Create Date: 2022-11-28 17:56:14.776735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89064e59a95d'
down_revision = '6158058da083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('display_responsibility', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'display_responsibility')
    # ### end Alembic commands ###
